version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.17
    - image: circleci/postgres:9.6-alpine
      environment: # environment variables for primary container
        POSTGRES_USER: postgres
    working_directory: /delinkcious/github.com/the-gigi/delinkcious
    steps:
    - checkout
    - run:
        name: Update certificates
        command: apt-get --allow-releaseinfo-change update && apt upgrade -y
    - run:
        name: Get all dependencies
        command: |
          go mod download all
    - run:
        name: Test everything
        command: ginkgo -r -race -failFast -progress
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: build and push Docker images
        shell: /bin/bash
        command: |
          chmod +x ./build.sh
          ./build.sh





